apiVersion: v1
kind: Service
metadata:
     name: static-web-deployment
     labels:
       component: webserver
       app: days-app
spec:
     ports:
     - port: 80
       targetPort: 8080
       protocol: TCP
     selector:
       component: webserver
     type: NodePort


